## define the telluric wavelength calibration parameters for each orders
import numpy as np

cal_param_dict = {
	'nirspec':{
		'30':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
		'31':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
		'32':{'xcorr_range':40, 'outlier_rej':3., 	'pixel_range_start':10,	'pixel_range_end':-60 },
		'33':{'xcorr_range':25, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-50 },
		'34':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-50 },
		'35':{'xcorr_range':5, 	'outlier_rej':2., 	'pixel_range_start':10, 'pixel_range_end':-10},
		'36':{'xcorr_range':10, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-50 },
		'37':{'xcorr_range':10, 'outlier_rej':2.5, 	'pixel_range_start':10, 'pixel_range_end':-20 },
		'38':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':50, 'pixel_range_end':-20 },
		'39':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':50, 'pixel_range_end':-20 },
		'51':{'xcorr_range':10, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-90 },
		'52':{'xcorr_range':10, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-90 },
		'53':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-90 },
		'55':{'xcorr_range':5, 	'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-90 },
		'56':{'xcorr_range':5, 	'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-30 },
		'57':{'xcorr_range':20, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
		'58':{'xcorr_range':15, 'outlier_rej':2., 	'pixel_range_start':0, 	'pixel_range_end':-30 },
		'59':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
		'60':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':5, 	'pixel_range_end':-5 },
		'61':{'xcorr_range':10, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
		'62':{'xcorr_range':10, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
		'63':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
		'64':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
		'65':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
		'66':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':10,	'pixel_range_end':-1 },
		},
	'igrins':{
		'77': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'109':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'110':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'111':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'112':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'113':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'114':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'115':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'116':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'117':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'118':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'119':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'120':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'121':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'122':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'123':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		'124':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
		},
	'fire':{
		'7':  {'xcorr_range':2.0, 'outlier_rej':2.5, 	'pixel_range_start':240, 	'pixel_range_end':-1170},
		'9':  {'xcorr_range':2.0, 'outlier_rej':2.5, 	'pixel_range_start':260, 	'pixel_range_end':-1010},
		'11': {'xcorr_range':2.0, 'outlier_rej':2.5, 	'pixel_range_start':30, 	'pixel_range_end':-1070},
		'14': {'xcorr_range':2.0, 'outlier_rej':2.5, 	'pixel_range_start':80, 	'pixel_range_end':-815},
		'15': {'xcorr_range':2.0, 'outlier_rej':2.5, 	'pixel_range_start':200, 	'pixel_range_end':-645},
		'19': {'xcorr_range':10.0, 'outlier_rej':2.5, 	'pixel_range_start':575, 	'pixel_range_end':-50},
		'20': {'xcorr_range':80.0, 'outlier_rej':2.5, 	'pixel_range_start':875, 	'pixel_range_end':-1},
	},
	'nires':{
		'ALL': {'xcorr_range':50.0, 'outlier_rej':2.5, 	'pixel_range_start':0, 	'pixel_range_end':-1},
	},
}

